services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: vlad
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb+srv://vladischanov:Glf2vHpT1CeNROOU@cluster0.7qifc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client:/app

  parsers:
    build:
      context: ./parsers
      dockerfile: Dockerfile.parsers
    container_name: parsers
    volumes:
      - ./parsers:/app

volumes:
  mongo-data:
